
version: '3'

services:

  shard1svr1:
    container_name: shard1svr1
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db --keyFile "/etc/key.file"  --auth
    ports:
      - 27020:27017
    volumes:
      - shard1svr1:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file


  shard1svr2:
    container_name: shard1svr2
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db --keyFile "/etc/key.file"  --auth
    ports:
      - 27021:27017
    volumes:
      - shard1svr2:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file

  shard1svr3:
    container_name: shard1svr3
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db --keyFile "/etc/key.file"  --auth
    ports:
      - 27022:27017
    volumes:
      - shard1svr3:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file

volumes:
  shard1svr1: {}
  shard1svr2: {}
  shard1svr3: {}

