
version: '3'

services:

  shard1svr1-product:
    container_name: shard1svr1-product
    image: mongo
    command: mongod --shardsvr --replSet shard1rs-product --port 27017 --dbpath /data/db 
    ports:
      - 5010:27017
    volumes:
      - shard1svr1-product:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file
    restart: always


  shard1svr2-product:
    container_name: shard1svr2-product
    image: mongo
    command: mongod --shardsvr --replSet shard1rs-product --port 27017 --dbpath /data/db 
    ports:
      - 5011:27017
    volumes:
      - shard1svr2-product:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file
    restart: always

  shard1svr3-product:
    container_name: shard1svr3-product
    image: mongo
    command: mongod --shardsvr --replSet shard1rs-product --port 27017 --dbpath /data/db 
    ports:
      - 5012:27017
    volumes:
      - shard1svr3-product:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file
    restart: always

volumes:
  shard1svr1-product: {}
  shard1svr2-product: {}
  shard1svr3-product: {}

