
version: '3'

services:

  shard1svr1-user:
    container_name: shard1svr1-user
    image: mongo
    command: mongod --shardsvr --replSet shard1rs-user --port 27017 --dbpath /data/db 
    ports:
      - 5030:27017
    volumes:
      - shard1svr1-user:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file


  shard1svr2-user:
    container_name: shard1svr2-user
    image: mongo
    command: mongod --shardsvr --replSet shard1rs-user --port 27017 --dbpath /data/db 
    ports:
      - 5031:27017
    volumes:
      - shard1svr2-user:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file

  shard1svr3-user:
    container_name: shard1svr3-user
    image: mongo
    command: mongod --shardsvr --replSet shard1rs-user --port 27017 --dbpath /data/db 
    ports:
      - 5032:27017
    volumes:
      - shard1svr3-user:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file

volumes:
  shard1svr1-user: {}
  shard1svr2-user: {}
  shard1svr3-user: {}

