version: '3'

services:
  cfgsvr:
    container_name: cfgsvr-product
    image: mongo
    command: mongod --configsvr --replSet cfgrs-product --port 27017 --dbpath /data/db
    ports:
      - 4010:27017
    volumes:
      - cfgsvr-product:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file


volumes:
  cfgsvr-product: {}