version: '3'

services:
  cfgsvr:
    container_name: cfgsvr
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db --keyFile "/etc/key.file"  --auth
    ports:
      - 27019:27017
    volumes:
      - cfgsvr:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file


volumes:
  cfgsvr: {}