version: '3'

services:
  cfgsvr-card:
    container_name: cfgsvr-card
    image: mongo
    command: mongod --configsvr --replSet cfgrs-card --port 27017 --dbpath /data/db
    ports:
      - 4000:27017
    volumes:
      - cfgsvr-card:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file
    restart: always

volumes:
  cfgsvr-card: {}