
version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos -configdb cfgrs/${eth0ip}:4010  --bind_ip 0.0.0.0 --port 27017
    ports:
      - 6010:27017
    volumes:
      - mongos:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file


volumes:
  mongos: {}