
version: '3'

services:

  mongos-card:
    container_name: mongos-card
    image: mongo
    command: mongos -configdb cfgrs-card/${eth0ip}:4000  --bind_ip 0.0.0.0 --port 27017
    ports:
      - 6000:27017
    volumes:
      - mongos-card:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file
    restart: always

volumes:
  mongos-card: {}