
version: '3'

services:

  mongos-user:
    container_name: mongos-user
    image: mongo
    command: mongos -configdb cfgrs-user/${eth0ip}:4010  --bind_ip 0.0.0.0 --port 27017
    ports:
      - 6020:27017
    volumes:
      - mongos-user:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file


volumes:
  mongos-user: {}