
version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos -configdb cfgrs/192.168.1.7:27019  --bind_ip 0.0.0.0 --port 27017
    ports:
      - 27017:27017
    volumes:
      - mongos:/data/db
    networks:
      - mongonet

volumes:
  mongos: {}
networks:
  mongonet:
    external:
      name: mongonet
