
version: '3'

services:

  shard2svr1-product:
    container_name: shard2svr1-product
    image: mongo
    command: mongod --shardsvr --replSet shard2rs-product --port 27017 --dbpath /data/db
    ports:
      - 5013:27017
    volumes:
      - shard2svr1-product:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file
    restart: always


  shard2svr2-product:
    container_name: shard2svr2-product
    image: mongo
    command: mongod --shardsvr --replSet shard2rs-product --port 27017 --dbpath /data/db
    ports:
      - 5014:27017
    volumes:
      - shard2svr2-product:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file
    restart: always

  shard2svr3-product:
    container_name: shard2svr3-product
    image: mongo
    command: mongod --shardsvr --replSet shard2rs-product --port 27017 --dbpath /data/db
    ports:
      - 5015:27017
    volumes:
      - shard2svr3-product:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file
    restart: always

volumes:
  shard2svr1-product: {}
  shard2svr2-product: {}
  shard2svr3-product: {}
