
version: '3'

services:

  shard2svr1:
    container_name: shard2svr1
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db --keyFile "/etc/key.file"  --auth
    ports:
      - 50004:27017
    volumes:
      - shard2svr1:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file


  shard2svr2:
    container_name: shard2svr2
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db --keyFile "/etc/key.file"  --auth
    ports:
      - 50005:27017
    volumes:
      - shard2svr2:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file

  shard2svr3:
    container_name: shard2svr3
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db --keyFile "/etc/key.file"  --auth
    ports:
      - 50006:27017
    volumes:
      - shard2svr3:/data/db
      - ../cnf/mongod.conf:/etc/mongod.conf
      - ../cnf/key.file:/etc/key.file

volumes:
  shard2svr1: {}
  shard2svr2: {}
  shard2svr3: {}
